# Generated by Django 5.0.5 on 2024-05-10 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Freelancer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=20)),
                ("lastname", models.CharField(max_length=20)),
                ("nationality", models.CharField(max_length=30)),
                ("age", models.CharField(max_length=3)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "photo_id",
                    models.ImageField(
                        blank=True, null=True, upload_to="freelancer_photos/"
                    ),
                ),
                ("email", models.CharField(max_length=50)),
                ("bio", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=4000)),
                (
                    "facebook_link",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "instagram_link",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "whatsapp_link",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "telegram_link",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "linkedin_link",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("viber_link", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "twitter_link",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("skype_link", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "tiktok_link",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "youtube_link",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "github_link",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "behance_link",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="freelancers", to="freelancers.category"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("education_description", models.CharField(max_length=200)),
                ("education_start_date", models.DateField()),
                ("education_end_date", models.DateField(blank=True, null=True)),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="freelancers.freelancer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_image",
                    models.ImageField(upload_to="certificate_images/"),
                ),
                ("description", models.CharField(max_length=400)),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="freelancers.freelancer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=400)),
                ("project_file", models.FileField(upload_to="project_files/")),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="freelancers.freelancer",
                    ),
                ),
            ],
        ),
    ]
